In [1]:
import numpy as np
import fhrr_driver_torch as fd
import torch
from matplotlib import pyplot as plt
import tqdm
import random

In [2]:
M_space = fd.fhrr_space(10000)
E_space = fd.fhrr_space(10000)
ME_map = fd.block_learning_map(M_space, E_space, 100, (100, 100), learn_rate=0.0001, decay_rate=0.0001)

In [3]:
A = M_space.init_random_vec()
B = M_space.init_random_vec()
C = M_space.init_random_vec()
M_vecs = torch.concat([A, B, C], axis=1)

In [4]:
for _ in range(5000):
    ME_map.learn(A, E_space.init_random_vec())
    ME_map.learn(B, E_space.init_random_vec())
    ME_map.learn(C, E_space.init_random_vec())

In [5]:
bundle = 0.2*A + 0.5 * B + 0.3*C
print(M_space.get_pdf(bundle, M_vecs))
new_bundle = ME_map.backwards(ME_map.forwards(bundle, normalize=True), normalize=True)
print(M_space.get_pdf(new_bundle, M_vecs))
new_bundle = ME_map.backwards(ME_map.forwards(new_bundle, normalize=True), normalize=True)
print(M_space.get_pdf(new_bundle, M_vecs))
new_bundle = ME_map.backwards(ME_map.forwards(new_bundle, normalize=True), normalize=True)
print(M_space.get_pdf(new_bundle, M_vecs))

tensor([[0.2007, 0.5003, 0.2989]])
tensor([[0.1791, 0.5754, 0.2455]])
tensor([[0.1569, 0.6389, 0.2042]])
tensor([[0.1434, 0.6756, 0.1809]])
