In [1]:
import torch

In [7]:
x = torch.arange(0, 20).reshape((2, 10)).T
print(x)

tensor([[ 0, 10],
        [ 1, 11],
        [ 2, 12],
        [ 3, 13],
        [ 4, 14],
        [ 5, 15],
        [ 6, 16],
        [ 7, 17],
        [ 8, 18],
        [ 9, 19]])


In [8]:
print(x.reshape((2, 5, -1)))

tensor([[[ 0, 10],
         [ 1, 11],
         [ 2, 12],
         [ 3, 13],
         [ 4, 14]],

        [[ 5, 15],
         [ 6, 16],
         [ 7, 17],
         [ 8, 18],
         [ 9, 19]]])


In [9]:
print(x.reshape((2, 5, -1)).reshape((10, -1)))

tensor([[ 0, 10],
        [ 1, 11],
        [ 2, 12],
        [ 3, 13],
        [ 4, 14],
        [ 5, 15],
        [ 6, 16],
        [ 7, 17],
        [ 8, 18],
        [ 9, 19]])
